jobs:
  ci:
    name: Check
    runs-on: ubuntu-20.04

    steps:
      - name: Begin
        uses: actions/checkout@v2
      - name: Pull Deps
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Test
        run: ./action/check

name: Main

on:
  schedule:
    - cron: "40 */6 * * *"
